# Generated by Django 4.1.1 on 2022-12-14 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_remove_product_stock_and_more'),
        ('wishlist', '0002_remove_wishlistitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
        migrations.DeleteModel(
            name='wishlistItem',
        ),
    ]
