# Generated by Django 4.1.1 on 2022-12-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(error_messages={'key': 'product price should be positive'}),
        ),
    ]
