# Generated by Django 4.1.1 on 2022-12-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
