# Generated by Django 4.1.1 on 2022-11-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
