# Generated by Django 4.1.1 on 2022-12-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_sub_category_offer_brandoffer_brand_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='stock_price',
        ),
    ]
