# Generated by Django 4.1.1 on 2022-12-29 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_reviewratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewratings',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
