# Generated by Django 4.1.1 on 2022-12-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_reviewratings_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.CharField(choices=[('Cotton', 'Cotton'), ('Spandex', 'Spandex'), ('Polyester', 'Polyester')], max_length=25)),
                ('wash_care', models.CharField(choices=[('Machine wash', 'Machine wash'), ('Handwash', 'Handwash'), ('Any wash', 'Any wash')], max_length=25)),
                ('fit', models.CharField(choices=[('Regular', 'Regular'), ('Slimfit', 'Slimfit'), ('Baggy fit', 'Baggy fit')], max_length=25)),
                ('occasion', models.CharField(choices=[('Athletic', 'Athletic'), ('Football', 'Football'), ('Gym-wear', 'Gym-wear'), ('Cricket', 'Cricket'), ('Other', 'Other')], max_length=25)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
