# Generated by Django 4.1.1 on 2022-12-29 11:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productattributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='brand_offer',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_offer',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brandoffer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category_offer',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcategoryoffer'),
        ),
        migrations.AlterField(
            model_name='subcategoryoffer',
            name='sub_category_offer',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
