# Generated by Django 4.1.1 on 2022-12-29 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('store', '0018_alter_brandoffer_brand_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand', unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoryoffer',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', unique=True),
        ),
    ]
