# Generated by Django 4.1.1 on 2022-12-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.brandoffer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.subcategoryoffer'),
        ),
    ]
