# Generated by Django 4.1.1 on 2022-12-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='cart_id',
            new_name='wishlist_id',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='cart',
            new_name='wishlist',
        ),
    ]
