# Generated by Django 4.1.1 on 2022-12-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_rename_cart_id_wishlist_wishlist_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='wishlistItem',
        ),
    ]
