# Generated by Django 4.1.1 on 2022-11-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='category_name',
        ),
    ]
