# Generated by Django 4.1.1 on 2022-11-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
