# Generated by Django 4.1.1 on 2022-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcat_name',
            field=models.CharField(max_length=50),
        ),
    ]
