# Generated by Django 4.1.1 on 2022-12-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userprofile_adress_useradress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradress',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useradress',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useradress',
            name='pin_code',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
