# Generated by Django 4.1.1 on 2022-12-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_useradress_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
    ]
