# Generated by Django 4.1.1 on 2022-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin_code',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
