# Generated by Django 4.1.1 on 2022-12-13 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_stock_and_more'),
        ('orders', '0011_alter_orderproduct_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
            preserve_default=False,
        ),
    ]
