# Generated by Django 4.1.1 on 2022-12-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adress_line_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='adress_line_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
