# Generated by Django 4.1.1 on 2022-12-15 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_useradress_pin_code'),
        ('orders', '0018_remove_order_adress_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.useradress'),
        ),
    ]
